#!/usr/bin/env python3
"""Sync Discord scheduled events directly into Supabase community_events.

Discord scheduled events are already structured enough to load automatically.
Free-form channel posts still go through the review-needed flow generated by
scripts/build_event_review_report.py.
"""

from __future__ import annotations

import json
import os
import sys
import argparse
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen


API_BASE = "https://discord.com/api/v10"
USER_AGENT = "fire-community-map-scheduled-events-sync/0.1"

STATUS_LABELS = {
    1: "scheduled",
    2: "active",
    3: "completed",
    4: "cancelled",
}

ENTITY_TYPE_LABELS = {
    1: "stage_instance",
    2: "voice",
    3: "external",
}

PRIVATE_EVENT_MARKERS = (
    "【メモ】",
    "[メモ]",
    "メモ",
    "出演者のみ",
    "内部",
    "非公開",
    "収録",
)


def load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("\"'"))


def require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def request_json(method: str, url: str, headers: dict[str, str], body: Any = None, retries: int = 2) -> Any:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = Request(url, data=data, headers=headers, method=method)
    try:
        with urlopen(req, timeout=30) as res:
            raw = res.read()
            return json.loads(raw) if raw else None
    except HTTPError as exc:
        body_text = exc.read().decode("utf-8", errors="replace")
        if exc.code == 429 and retries > 0:
            try:
                retry_after = float(json.loads(body_text).get("retry_after", 5))
            except (ValueError, json.JSONDecodeError, TypeError):
                retry_after = 5
            time.sleep(retry_after + 0.5)
            return request_json(method, url, headers, body, retries - 1)
        raise RuntimeError(f"HTTP {exc.code} for {method} {url}: {body_text}") from exc
    except URLError as exc:
        raise RuntimeError(f"Request failed for {method} {url}: {exc}") from exc


def discord_get(path: str, token: str, query: dict[str, str] | None = None) -> Any:
    url = f"{API_BASE}{path}"
    if query:
        url = f"{url}?{urlencode(query)}"
    return request_json("GET", url, {"Authorization": f"Bot {token}", "User-Agent": USER_AGENT})


def supabase_request(method: str, url: str, service_role_key: str, body: Any = None) -> Any:
    return request_json(
        method,
        url,
        {
            "apikey": service_role_key,
            "Authorization": f"Bearer {service_role_key}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates,return=minimal",
        },
        body,
    )


def channel_names(token: str, guild_id: str) -> dict[str, str]:
    channels = discord_get(f"/guilds/{guild_id}/channels", token)
    return {str(c["id"]): str(c.get("name") or "") for c in channels}


def scheduled_events(token: str, guild_id: str) -> list[dict[str, Any]]:
    return discord_get(
        f"/guilds/{guild_id}/scheduled-events",
        token,
        {"with_user_count": "true"},
    )


def infer_tags(event: dict[str, Any], channel_name: str | None) -> list[str]:
    name = str(event.get("name") or "")
    haystack = f"{name} {channel_name or ''}"
    tags: list[str] = []
    entity_type = ENTITY_TYPE_LABELS.get(event.get("entity_type"), str(event.get("entity_type")))
    tags.append("オンライン" if entity_type in {"voice", "stage_instance"} else "オフ会")
    if "麻雀" in haystack or "ゲーム" in haystack:
        tags.append("ゲーム")
    if "飲み" in haystack or "交流" in haystack:
        tags.append("交流会")
    if "寺子屋" in haystack or "寺小屋" in haystack or "分析" in haystack:
        tags.append("勉強会")
    if "打ち合わせ" in haystack:
        tags.append("打ち合わせ")
    if "メモ" in haystack:
        tags.append("メモ")
    if "収録" in haystack or "YouTube" in haystack or "youtube" in haystack.lower():
        tags.append("収録")
    return list(dict.fromkeys(tags))


def is_public_event(event: dict[str, Any], channel_name: str | None) -> bool:
    text = " ".join(
        str(value or "")
        for value in (
            event.get("name"),
            event.get("description"),
            channel_name,
        )
    )
    return not any(marker in text for marker in PRIVATE_EVENT_MARKERS)


def event_row(event: dict[str, Any], guild_id: str, channel_names_by_id: dict[str, str]) -> dict[str, Any]:
    event_id = str(event["id"])
    channel_id = str(event.get("channel_id") or "")
    channel_name = channel_names_by_id.get(channel_id)
    entity_type = ENTITY_TYPE_LABELS.get(event.get("entity_type"), str(event.get("entity_type")))
    metadata = event.get("entity_metadata") or {}
    external_location = metadata.get("location")
    is_online = entity_type in {"voice", "stage_instance"}
    location_label = external_location or (f"Discord / {channel_name}" if channel_name else "Discord")
    description = str(event.get("description") or "").strip()
    status = STATUS_LABELS.get(event.get("status"), str(event.get("status")))
    return {
        "title": str(event.get("name") or "無題のDiscordイベント"),
        "tags": infer_tags(event, channel_name),
        "starts_at": event.get("scheduled_start_time"),
        "ends_at": event.get("scheduled_end_time"),
        "format": "online" if is_online else "offline",
        "prefecture": "オンライン" if is_online else None,
        "location_label": location_label,
        "participant_count": event.get("user_count"),
        "participation_note": "Discordのサーバーイベントから参加。",
        "summary": description or "Discordのイベント作成機能で予定されているイベント。",
        "discord_channel_name": channel_name,
        "discord_message_id": f"scheduled_event:{event_id}",
        "discord_permalink": f"https://discord.com/events/{guild_id}/{event_id}",
        "cancelled_at": datetime.now(timezone.utc).isoformat() if status == "cancelled" else None,
    }


def delete_events(supabase_url: str, service_role_key: str, discord_message_ids: list[str]) -> None:
    if not discord_message_ids:
        return
    ids_csv = ",".join(discord_message_ids)
    query = urlencode({"discord_message_id": f"in.({ids_csv})"}, safe="(),.:")
    request_json(
        "DELETE",
        f"{supabase_url}/rest/v1/community_events?{query}",
        {
            "apikey": service_role_key,
            "Authorization": f"Bearer {service_role_key}",
        },
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Discord scheduled events into Supabase.")
    parser.add_argument("--env-file", default=os.environ.get("ENV_FILE", ".env"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    load_dotenv(Path(args.env_file))
    token = require_env("DISCORD_BOT_TOKEN")
    guild_id = require_env("DISCORD_GUILD_ID")
    supabase_url = require_env("SUPABASE_URL")
    service_role_key = require_env("SUPABASE_SERVICE_ROLE_KEY")

    names = channel_names(token, guild_id)
    events = scheduled_events(token, guild_id)
    private_ids = [
        f"scheduled_event:{event['id']}"
        for event in events
        if event.get("scheduled_start_time") and not is_public_event(event, names.get(str(event.get("channel_id") or "")))
    ]
    rows = [
        event_row(event, guild_id, names)
        for event in events
        if event.get("scheduled_start_time") and is_public_event(event, names.get(str(event.get("channel_id") or "")))
    ]
    print(f"Prepared {len(rows)} Discord scheduled events.")
    print(f"Private scheduled events to delete: {len(private_ids)}")
    if args.dry_run:
        if private_ids:
            print(json.dumps({"delete_discord_message_ids": private_ids}, ensure_ascii=False, indent=2))
        print(json.dumps(rows, ensure_ascii=False, indent=2))
        return 0
    if rows:
        supabase_request(
            "POST",
            f"{supabase_url}/rest/v1/community_events?on_conflict=discord_message_id",
            service_role_key,
            rows,
        )
        print("Upserted Discord scheduled events into community_events.")
    if private_ids:
        delete_events(supabase_url, service_role_key, private_ids)
        print("Deleted private scheduled events from community_events.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
